#!/bin/sh
#(obfuscated to shrink download size by ryan.)
#Copyright 2006, Kevin Krammer <kevin.krammer@gmx.at>
#Copyright 2006, Jeremy White <jwhite@codeweavers.com>
#LICENSE:
#Permission is hereby granted, free of charge, to any person obtaining a
#copy of this software and associated documentation files (the "Software"),
#to deal in the Software without restriction, including without limitation
#the rights to use, copy, modify, merge, publish, distribute, sublicense,
#and/or sell copies of the Software, and to permit persons to whom the
#Software is furnished to do so, subject to the following conditions:
#The above copyright notice and this permission notice shall be included
#in all copies or substantial portions of the Software.
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
#OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
#ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
#OTHER DEALINGS IN THE SOFTWARE.
f1()
{
if [ ! -e "$1" ]; then
exit 2
fi
if [ ! -r "$1" ]; then
exit 5
fi
}
f2()
{
aa="$2"
[ -n "$aa" ] || aa="filename"
ab=`basename "$1"`
case "$ab" in
[a-zA-Z]*-*)
return
;;
esac
exit 1
}
ac=" > /dev/null 2> /dev/null"
f3()
{
if [ "$as" = "system" ] ; then
for x in `echo $PATH | sed 's/:/ /g'` /opt/gnome/bin; do
if [ -x $x/update-desktop-database ] ; then
eval '$x/update-desktop-database'$ac
return
fi
done
fi
}
f4()
{
awk '
BEGIN {
    xlat["AudioVideo"]="X-Mandrakelinux-Multimedia;X-MandrivaLinux-Multimedia"
    xlat["Development"]="X-Mandrakelinux-MoreApplications-Development;X-MandrivaLinux-MoreApplications-Development"
    xlat["Education"]="X-Mandrakelinux-MoreApplications;X-MandrivaLinux-MoreApplications-Education"
    xlat["Game"]="X-Mandrakelinux-MoreApplications;X-MandrivaLinux-MoreApplications-Games"
    xlat["Graphics"]="X-Mandrakelinux-Multimedia-Graphics"
    xlat["Network"]="X-Mandrakelinux-Internet;X-MandrivaLinux-Internet"
    xlat["Office"]="X-Mandrakelinux-Office;X-MandrivaLinux-Office"
    xlat["System"]="X-Mandrakelinux-System;X-MandrivaLinux-System"
    xlat["Utility"]="X-Mandrakelinux-Office-Accessories;X-MandrivaLinux-Office-Accessories"
}
{
if (match($0,/Categories=/)) {
split(substr($0,RSTART+11),categories,";")
result=""
for (n in categories)
{
if (categories[n] in xlat)
categories[n]=categories[n] ";" xlat[categories[n]]
if (categories[n])
result=result categories[n] ";"
}
print "Categories=" result
}
else
{
print $0
}
}' $1 > $1.new
mv $1.new $1
}
f5()
{
local ad
local ae
local af
ad=`awk '
{
if (match($0,/MimeType=/)) {
split(substr($0,RSTART+9),mimetypes,";")
for (n in mimetypes)
{
if (mimetypes[n])
print mimetypes[n]
}
}
}' "$1/$2" 2> /dev/null`
for MIME in $ad ; do
af="$XDG_DATA_DIRS"
[ -n "$af" ] || af=/usr/local/share/:/usr/share/
if [ x"$as" = x"user" ] ; then
ae="$XDG_DATA_HOME"
[ -n "$ae" ] || ae="$HOME/.local/share"
af="$ae:$af"
fi
local ag
for x in `echo "$af" | sed 's/:/ /g'`; do
ag=`grep "$MIME=" $x/applications/defaults.list 2> /dev/null | cut -d '=' -f 2`
if [ -n "$ag" ] ; then
ag="$ag;"
break;
fi
done
if echo "$ag" | grep "$2" $ac ; then
continue;
fi
aj="$1/defaults.list"
grep -v "$MIME=" $aj > ${aj}.new 2> /dev/null
if ! grep "[Default Applications]" ${aj}.new > /dev/null; then
echo "[Default Applications]" >> ${aj}.new
fi
echo $MIME="$ag$2" >> ${aj}.new
mv ${aj}.new $aj
done
}
f6()
{
ah="$1"
ai=menus
ae="$XDG_CONFIG_HOME"
[ -n "$ae" ] || ae="$HOME/.config"
ae="$ae/$ai"
bm="$XDG_CONFIG_DIRS"
[ -n "$bm" ] || bm=/etc/xdg
ak=
for x in `echo $bm | sed 's/:/ /g'` ; do
if [ -w $x/$ai ] ; then
ak="$x/$ai"
break
fi
done
ae="$ae/applications-merged"
ak="$ak/applications-merged"
if [ x"$as" = x"user" ] ; then
ao="$ae"
at="$aw"
au="$av"
ax=077
ay=0600
else
ao="$ak"
at="$al"
au="$am"
ax=022
ay=0644
if [ -z "${ao}${at}${au}" ] ; then
exit 3
fi
fi
if [ -z "$ah" ] ; then
bo=`umask`
umask $ax
mkdir -p $ao
touch $ao/xdg-desktop-menu-dummy.menu
umask $bo
return
fi
if [ $be = "install" -a -f "/etc/xdg/menus/gnome-applications.menu" ] ; then
aq=`echo "$ao" | sed -e 's^/applications-merged^/gnome-applications-merged^'`
if [ ! -e "$aq" ] ; then
mkdir -p `dirname "$aq"`
eval 'ln -s "applications-merged" "$aq"'$ac
fi
fi
if [ $be = "install" -a -f "/etc/mandrake-release" ] ; then
ar=`echo "$ao" | sed -e 's^/applications-merged^/applications-mdk-merged^'`
if [ ! -e "$ar" ] ; then
mkdir -p `dirname "$ar"`
eval 'ln -s "applications-merged" "$ar"'$ac
fi
fi
if [ $be = "install" -a x"$as" = x"user" -a -d "/etc/xdg/menus/kde-applications-merged" ] ; then
ap=`echo "$ao" | sed -e 's^/applications-merged^/kde-applications-merged^'`
if [ ! -e "$ap" ] ; then
mkdir -p `dirname "$ap"`
eval 'ln -s "applications-merged" "$ap"'$ac
fi
fi
if [ $be = "install" -a x"$as" = x"system" -a -d "/etc/xdg/menus/kde-applications-merged" -a ! -d "/etc/xdg/menus/applications-merged" ] ; then
ap=`echo "$ao" | sed -e 's^/applications-merged^/kde-applications-merged^'`
eval 'ln -s "kde-applications-merged" "$ao"'$ac
fi
bp=$ao/$ah
test "${TMPDIR+set}" = set || TMPDIR=/tmp
az=`mktemp $TMPDIR/tmp.XXXXXXXXXX`
bi=
if [ -r "$bp" ] ; then
awk '
BEGIN {
  RS="<"
}
/^Filename/ {
if (match($0,/>/)) {
print substr($0,RSTART+1)
}
}' $bp > $az
fi
bi=`cat $az`
bj=
if [ $be = "install" ] ; then
for bl in $bk; do
bc=`basename $bl`
if ! grep '^'$bc'$' $az $ac ; then
echo "$bc" >> $az
fi
done
bj=`cat $az`
fi
if [ $be = "uninstall" ] ; then
echo > $az
for bl in $bk; do
echo "$bl" >> $az
done
for bl in $bi; do
if ! grep '^'$bl'$' $az $ac ; then
bj="$bj $bl"
fi
done
fi
rm -f "$az"
if [ -n "$bj" ] ; then
test "${TMPDIR+set}" = set || TMPDIR=/tmp
az=`mktemp $TMPDIR/tmp.XXXXXXXXXX`
(
echo '<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"'
echo '    "http://www.freedesktop.org/standards/menu-spec/menu-1.0.dtd">'
echo '<!-- Do not edit manually - generated and managed by xdg-desktop-menu -->'
echo '<Menu>'
echo '    <Name>Applications</Name>'
for bl in $bg; do
bc=`basename $bl`
bb=`echo "$bc"|cut -d '.' -f 1`
echo "<Menu>"
echo "    <Name>$bb</Name>"
echo "    <Directory>$bc</Directory>"
done
echo "    <Include>"
for bl in $bj; do
echo "        <Filename>$bl</Filename>"
done
echo "    </Include>"
for bl in $bg; do
echo "</Menu>"
done
echo '</Menu>'
) > $az
chmod $ay $az
bo=`umask`
umask $ax
mkdir -p $ao
eval 'cp $az $ao/$ah'$ac
umask $bo
rm -f "$az"
else
rm -f $ao/$ah
fi
if [ $be = "uninstall" ] ; then
test "${TMPDIR+set}" = set || TMPDIR=/tmp
az=`mktemp $TMPDIR/tmp.XXXXXXXXXX`
for ah in $ao/*; do
if grep 'generated and managed by xdg-desktop-menu' $ah $ac ; then
awk '
BEGIN {
  RS="<"
}
/^Directory/ {
if (match($0,/>/)) {
print substr($0,RSTART+1)
}
}' $ah >> $az
fi
done
bh="$bg"
bg=
for bl in $bh; do
if ! grep '^'$bl'$' $az $ac ; then
bg="$bg $bl"
fi
done
rm -f "$az"
fi
}
[ x"$1" != x"" ] || exit 1
as=
be=
bd=yes
bk=
bg=
case $1 in
install)
be=install
;;
uninstall)
be=uninstall
;;
forceupdate)
be=forceupdate
;;
*)
exit 1
;;
esac
shift
bf=true
while [ $# -gt 0 ] ; do
bn="$1"
shift
case "$bn" in
--noupdate)
bd=no
;;
--mode)
if [ -z "$1" ] ; then
exit 1
fi
case "$1" in
user)
as="user"
;;
system)
as="system"
;;
*)
exit 1
;;
esac
shift
;;
--novendor)
bf=false
;;
-*)
exit 1
;;
*)
if [ "$be" = "install" ] ; then
f1 "$bn"
fi
case "$bn" in
*.directory)
if [ -n "$bk" ] ; then
exit 1
fi
bg="$bg $bn"
;;
*.desktop)
bk="$bk $bn"
;;
*)
exit 1
;;
esac
;;
esac
done
if [ -z "$be" ] ; then
exit 1
fi
if [ -n "$XDG_UTILS_INSTALL_MODE" ] ; then
if [ "$XDG_UTILS_INSTALL_MODE" = "system" ] ; then
as="system"
elif [ "$XDG_UTILS_INSTALL_MODE" = "user" ] ; then
as="user"
fi
fi
if [ -z "$as" ] ; then
if [ `whoami` = "root" ] ; then
as="system"
else
as="user"
fi
fi
if [ x"$be" = x"forceupdate" ] ; then
f3
exit 0
fi
if [ -z "$bk" ] ; then
exit 1
fi
ba=
for bl in $bg; do
if [ "$bf" =  "true" -a "$be" = "install" ] ; then
f2 "$bl"
fi
bb=`basename "$bl"|cut -d '.' -f 1`
if [ -z "$ba" ] ; then
ba="$bb"
else
ba="$ba-$bb"
fi
done
if [ -n "$ba" ] ; then
if [ x"$as" = x"user" ] ; then
f6 "user-$ba.menu"
else
f6 "$ba.menu"
fi
else
if [ x"$as" = x"user" ] ; then
f6
fi
fi
ai=desktop-directories
ae="$XDG_DATA_HOME"
[ -n "$ae" ] || ae="$HOME/.local/share"
ae="$ae/$ai"
bm="$XDG_DATA_DIRS"
[ -n "$bm" ] || bm=/usr/local/share/:/usr/share/
ak=
for x in `echo $bm | sed 's/:/ /g'` ; do
if [ -w $x/$ai ] ; then
ak="$x/$ai"
break
fi
done
if [ x"$as" = x"user" ] ; then
ao="$ae"
at="$aw"
au="$av"
ax=077
else
ao="$ak"
at="$al"
au="$am"
ax=022
if [ -z "${ao}${at}${au}" ] ; then
exit 3
fi
fi
for bl in $bg; do
bc=`basename $bl`
case $be in
install)
bo=`umask`
umask $ax
for x in $ao $at $au ; do
mkdir -p $x
eval 'cp $bl $x/$bc'$ac
done
umask $bo
;;
uninstall)
for x in $ao $at $au ; do
rm -f $x/$bc
done
;;
esac
done
ai=applications
ae="$XDG_DATA_HOME"
[ -n "$ae" ] || ae="$HOME/.local/share"
ae="$ae/$ai"
bm="$XDG_DATA_DIRS"
[ -n "$bm" ] || bm=/usr/local/share/:/usr/share/
ak=
for x in `echo $bm | sed 's/:/ /g'` ; do
if [ -w $x/$ai ] ; then
ak="$x/$ai"
break
fi
done
aw="$HOME/.kde/share/applnk"
al="/usr/share/applnk"
[ -w $al ] || al=
av="$HOME/.gnome/apps"
am="/usr/share/gnome/apps"
[ -w $am ] || am=
[ -f /etc/mandriva-release ] && an=true
if [ x"$as" = x"user" ] ; then
ao="$ae"
at="$aw"
au="$av"
ax=077
else
ao="$ak"
at="$al"
au="$am"
ax=022
if [ -z "${ao}${at}${au}" ] ; then
exit 3
fi
fi
for bl in $bk; do
if [ "$bf" =  "true" -a "$be" = "install" ] ; then
f2 "$bl"
fi
bc=`basename $bl`
case $be in
install)
bo=`umask`
umask $ax
for x in $ao $at $au ; do
mkdir -p $x
eval 'cp $bl $x/$bc'$ac
done
if [ -n "$an" ] ; then
f4 $ao/$bc
fi
if [ -f $at/$bc ] ; then
echo "OnlyShowIn=Old;" >> $at/$bc
fi
if [ -f $au/$bc ] ; then
echo "OnlyShowIn=Old;" >> $au/$bc
fi
f5 "$ao" "$bc"
umask $bo
;;
uninstall)
for x in $ao $at $au ; do
rm -f $x/$bc
done
;;
esac
done
if [ x"$bd" = x"yes" ] ; then
f3
fi
exit 0
