name: Build

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Linux,   os: ubuntu-20.04, flags: -GNinja }
        #- { name: Windows, os: windows-latest }
        #- { name: MacOS,   os: macos-latest }
    steps:
    - name: Setup Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build libgtk2.0-dev libgtk-3-dev libncursesw5-dev
    - name: Get mojosetup sources
      uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B build ${{ matrix.platform.flags }}
    - name: Build
      run: cmake --build build/
